#!/bin/bash
# One-shot install of the harness-lark Feishu plugin into a dsh profile.
#
# Usage:
#   export FEISHU_APP_ID=cli_xxx
#   export FEISHU_APP_SECRET=your_secret
#   bash scripts/install-dsh.sh [profile] [plugin-source]
#
#   profile:      dsh profile name (default: web)
#   plugin-source: npm package name or local path; defaults to `harness-lark`
#                  (published npm package). For a local checkout use the repo
#                  path, e.g. `bash scripts/install-dsh.sh web .`
#
# The script:
#   1. installs the plugin into the profile (`dsh plugin --profile <p> add <src>`)
#   2. writes the profile's cordis.patch.yml (Feishu gateway config; existing
#      patch file is left untouched, so re-runs are safe)
#   3. starts `dsh --profile <p>` with optional --trusted-host args
#
# Prereqs: a working `dsh` CLI on PATH, and the profile's runtime deps
# (node >= 22, pnpm for out-of-tree installs).
set -e

PROFILE="${1:-web}"
PLUGIN_SOURCE="${2:-harness-lark}"
DSH_HOME="${DSH_HOME:-$HOME/.dsh}"
PROFILE_DIR="$DSH_HOME/profiles/$PROFILE"
PROFILE_PATCH="$PROFILE_DIR/cordis.patch.yml"

if [ -z "$FEISHU_APP_ID" ] || [ -z "$FEISHU_APP_SECRET" ]; then
  echo "error: FEISHU_APP_ID and FEISHU_APP_SECRET must be set" >&2
  exit 1
fi

echo "[harness-lark] installing plugin into profile '$PROFILE' from '$PLUGIN_SOURCE'..."
dsh plugin --profile "$PROFILE" add "$PLUGIN_SOURCE"

if [ ! -f "$PROFILE_PATCH" ]; then
  mkdir -p "$PROFILE_DIR"
  cat > "$PROFILE_PATCH" << PATCH
# harness-lark Feishu channel (generated by scripts/install-dsh.sh)
- id: lark
  config:
    appId: !!js process.env.FEISHU_APP_ID
    appSecret: !!js process.env.FEISHU_APP_SECRET
    brand: feishu
    connectionMode: websocket
    dmPolicy: open
    groupPolicy: open
    requireMentionInGroups: true
    respondToMentionAll: false
    replyMode: streaming
    topicSeparateSession: true
PATCH
  echo "[harness-lark] wrote $PROFILE_PATCH"
else
  echo "[harness-lark] $PROFILE_PATCH already exists, leaving untouched"
fi

echo "[harness-lark] starting dsh --profile $PROFILE..."
TRUSTED_ARGS=()
for authority in ${DSH_TRUSTED_HOSTS:-}; do
  TRUSTED_ARGS+=(--trusted-host "$authority")
done
exec dsh --profile "$PROFILE" "${TRUSTED_ARGS[@]}"
